### ISSUE TITLE
Update cython to 0.22

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1128]
We are a patch release behind cython latest (0.21.2 vs 0.22).

@doutriaux1 @aashish24 want to assign me to this task as a 2.3 milestone?

**Comment by jypeter** [comment]
Updating Cython will maybe make it possible to install more recent versions of netCDF4 ... But it seems that Paul already has a more recent version of Cython than what I have in my stock 2.1.0 UV-CDAT (**0.16**)

https://github.com/Unidata/netcdf4-python/issues/367

Not that I'm going to use netCDF4, because I prefer cdms2! :-) But some of my users want netCDF4...

**Comment by durack1** [comment]
@jypeter we're at the near bleeding edge of netcdf @ [4.3.2](https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/netcdf_pkg.cmake) in the upcoming 2.2, I'll likely bump the sources to the latest patch release [4.3.3.1](https://github.com/Unidata/netcdf-c/releases/tag/v4.3.3.1) as a 2.3 milestone..

**Comment by jypeter** [comment]
My concern is not about the latest version of netcdf, but the latest version of netcdf4-python! :)

That's he module (import netCDF4) that the unlucky souls who can't import cdms2 have to use (even when I give them access to UV-CDAT...)

http://unidata.github.io/netcdf4-python/

**Comment by durack1** [comment]
@doutriaux1 this is now a resolved by commits in #1324 (https://github.com/UV-CDAT/uvcdat/commit/20b5ac3873151391da438cf69f5e8e088de83058) closing..

**Comment by doutriaux1** [comment]
@durack1 yes, just awaiting from netcdf answers so i can issue the PR.
