### ISSUE TITLE
Removing VTK and checking if everything works correctly

### ISSUE THREAD

**Issue by hgohil2805** [UV-CDAT/uvcdat#1166]
Considering that VTK is not being used currently we will be removing VTK and check if everything works correctly. 
This will also help decrease the amount of time it takes to load uvcdat at the beginning.

**Comment by aashish24** [comment]
:1

**Comment by aashish24** [comment]
+1

**Comment by vvpalav** [comment]
Removed VTK from startup.xml and uvcdat_cdms did not load due to following error.

Package 'UVCDAT CDMS' failed to initialize because of the following exceptions: Traceback (most recent call last): File "/vistrails/vistrails/core/modules/module_registry.py", line 1454, in initialize_package self.auto_add_module(module) File "vistrails/vistrails/core/modules/module_registry.py", line 958, in auto_add_module return self.add_module(module) File "vistrails/vistrails/core/modules/module_registry.py", line 1114, in add_module raise MissingBaseClass(baseClass) MissingBaseClass: Base class has not been registered : packages.uvcdat.init.Plot 

does anyone have any idea?

**Comment by vvpalav** [comment]
@chaosphere2112 @aashish24 @doutriaux1 .. Hey I need your help on this issue.
We are trying to remove VTK so that loading of UV-CDAT GUI becomes faster.
As you guys worked on couple of issues related to GUI and VTK, can you please help me to know if VTK is currently used anywhere. Also how hard will it be to remove VTK or removing it doesn't make any sense. I have posted one issue I got above when I commented vtk package loading in startup.xml. 
Any help is highly appreciated and will help me to resolve this faster :-)

**Comment by doutriaux1** [comment]
I'm not sure if I can help. All I know is that when vistrails was coupled with uvcdat. Vcs  was not using vtk. So as far as vistrails and uvcdat working together goes there is no dependency on vtk. Since 2.1 vcs is now using vtk but only as a backend non of the vcs calls changed. The only place where I could see a dependency between vcs and vistrails nowadays is with the 3d bits. dv3d is now part of vcs. @ThomasMaxwell do you know if dv3d integration with vistrails depends on vtk? Thanks.

**Comment by aashish24** [comment]
@vvpalav we shouldn't use VTK via Vistrails in this case. I think it should be safe to remove it.

**Comment by ThomasMaxwell** [comment]
I’m not clear on whether you are referring to the VTK library, which is a requirement of vcs and UVCDAT, or the VTK package in vistrails, which provides an interface to the VTK library in vistrails, and AFAIK is not used by UVCDAT.

**Comment by doutriaux1** [comment]
The vtk package in vistrails

**Comment by vvpalav** [comment]
https://github.com/UV-CDAT/VisTrails/pull/37 .. Please review the pull request

**Comment by vvpalav** [comment]
@ThomasMaxwell .. Just need confirmation on following.
There is an import in most python files in vtDV3D package from vtk package like packages.vtk.base_module import vtkBaseModule

I checked if anything is used from this import, but could't find anything. Can you please confirm any code from this import is not used in dv3d?

Reference Import lines:
.//vistrails/packages/vtDV3D/CurtainPlotModule.py:12:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/LevelSurfaceModule.py:11:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/MultiVolumeSlicerModule.py:14:#from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/ParallelCoordinatesModule.py:14:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VectorCutPlaneModule.py:16:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VectorVolumeModule.py:16:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VolumeRenderModule.py:11:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VolumeSlicerModule.py:14:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VoxelizerModule.py:16:from packages.vtk.base_module import vtkBaseModule

We are going to remove vtk package from vistrails, for that we are planning to move few classes like QVTKWidget, QVTKWidgetToolBar into other package. Elsewhere vtk is not used in vistrails.

**Comment by remram44** [comment]
vtDV3D is very broken and mostly unused (see #17). You should ignore.

**Comment by remram44** [comment]
Closed by UV-CDAT/VisTrails#37
