### ISSUE TITLE
Enable Matplotlib in default build

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1406]

**Comment by jypeter** [comment]
I completely agree with this! These days, most python classes teach new users how to use matplotlib for plots, so it will be hard to convince potential users to switch to the uv-cdat distribution if matplotib is not available by default... You may want to bundle basemap as well

And you also want to **convince new users that cdms2+vcs is easier to use than netcdf4+matplotlib+basemap**. Well, at least you need less lines in cdms2+vcs to get a basic plot, which is often enough for interns... @chaosphere2112 , maybe you can use a variation of http://uvcdat.llnl.gov/display.php?file=test_vcs_patterns on the web site to show people how easy it is to make a basic plot. At least for data on regular grids

 - @chaosphere2112 btw, why is the example from the gallery above named *patterns*? I don't see any patterns

 - @doutriaux1 can the *new* vcs handle again projections created with *createprojection* ?

**Comment by aashish24** [comment]
@jypeter I personally think cdms2+vcs is way easier than netcdf4+matplotlib+basemap in terms of APi and ease of use. Also, unless you are doing mostly static plots (which I don't) matplotlib does not help as much. But I agree that we need to keep working on documentation, improving the code quality and stability, and improving the features to make it more convincing. Matplotlib is easy to deploy but basemap is not. We are trying to enable both by default.

**Comment by jypeter** [comment]
I don't remember having problems installing basemap, I thik it worked fine when I used  ```-D CDAT_BUILD_BASEMAP=ON  -D CDAT_BUILD_MATPLOTLIB=ON```. It's cartopy that is hard to install

 - cdms2+vcs gives you default maps faster than other packages for data on **regular grids**, and that's something we can sell to new users
 - But there are more and more *people using basemap to create plots for data on irregular grids*, and basemap may work in cases where meshfill does not. I think the basemap graphics methods are not as picky as meshfill and do not require the specification of cell boundaries. But I'm no specialist and really suck at plotting this kind of data. Basemap also provides more graphics methods for irregular grids than just 'fill'. It may be interesting to see how basemap can actually plot things without knowing about the cell boundaries, and how accurate the plots are
 - there are some meshfill examples in the uvcdat gallery, but there is no in-depth explanation on how to use meshfill (what are the requirements on the input data to make it work, ...), and nothing at all about meshfill in http://uvcdat.llnl.gov/documentation/vcs/vcs-11.html. Searching the site for meshfill mostly return hits in the gallery
 - now that I think of it, having a better (or better documented) meshfill may help switch some ferret users to uvcdat, rather than having people insisting on having pyferret (I have not tried installing this at all)

Maybe this should be split in several issues, both for uvcdat and uvcdat-site. But it's so hoooot here, and we don't have any AC :(

**Comment by doutriaux1** [comment]
@jypeter I have to double check but isofill/isoline should work on irregular grids now as well.

**Comment by aashish24** [comment]
@jypeter can you describe irregular grids? Since we use VTK on the backend, we can support lot many grid types (lot more than basemap) so if we are missing something it will be pretty easy to add. Basemap has lot more dependencies and that's why it is harder to build.

**Comment by jypeter** [comment]
RTFM :)
http://uvcdat.llnl.gov/documentation/cdms/cdms_1.html#1.9

**Comment by jypeter** [comment]
@aashish24 I have asked some of our users to give me some variables on irregular grids. I will post the links to the data asap so that you can try to display them

**Comment by durack1** [comment]
@aashish24 @sankhesh this looks ready for closing by #1458

**Comment by doutriaux1** [comment]
@durack1 not yet we need basemap as well

**Comment by jypeter** [comment]
@aashish24 I have made some data on *irregular* grids available in #1465. I think it made more sense to start a new issue
