### ISSUE TITLE
can't switch to portrait mode while in background mode

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1446]
```python
import numpy
data=numpy.sin(numpy.arange(100))
data=numpy.reshape(data,(10,10))
import vcs
x=vcs.init()
x.plot(data,bg=1)
x.clear()
x.portrait()
```
leads to:
```
python: /home/doutriaux1/build/build/VTK/Rendering/OpenGL/vtkOpenGLRenderWindow.cxx:1603: int vtkOpenGLRenderWindow::CreateHardwareOffScreenWindow(int, int): Assertion `"pre: positive_width" && width>0' failed.
```

**Comment by sankhesh** [comment]
@doutriaux1 The issue comes from [Canvas.py::portrait()](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/Canvas.py#L4658-4663); whereby it calls `self.canvas.canvasinfo`. However, `canvasinfo` is **not** a member of the class `Canvas` defined [here](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/Canvas.py#L4306).

Is it just the indentation that is wrong when defining function `canvasinfo` ?

OR 

Should I change all references of `self.canvas.canvasinfo` to `self.canvasinfo`?

**Comment by doutriaux1** [comment]
@sankhesh it seems to be part of it. 
```python
In [5]: import vcs

In [6]: x=vcs.init()

In [7]: x.canvasinfo()
Out[7]: {'depth': None, 'height': 606, 'mapstate': False, 'width': 814, 'x': 0, 'y': 0}
```
I'm not sure I understand your question.

**Comment by sankhesh** [comment]
@doutriaux1 Sorry I framed the question wrong. 

What I meant was that `canvasinfo` is a member of class `Canvas` and hence should be used like: `dict = apply(self.canvasinfo, cargs)` instead of like `dict = apply(self.canvas.canvasinfo, cargs)` in  [Canvas.py::portrait()](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/Canvas.py#L4658-4663)

`self.canvas` returns `vcs` object as set [here](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/Canvas.py#L950)

So my question is whether `canvasinfo` was intended to be a member of `vcs`? 

If yes, I will have to change its indentation in the [Canvas.py](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/Canvas.py#L4306) file.

If no, I will have to change all references of `self.canvas.canvasinfo()` to `self.canvasinfo()`.
