### ISSUE TITLE
cdms2 seg fault on some weird types

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1857]
in the uvcmetrics code they have an attribute (temporary) that is some python class, cdms2 seg fault when creating the file attribute

**Comment by painter1** [comment]
The attribute is :filetable.  The segfault occurs when you write an object which has that attribute - cdms2 can write only its own objects, or strings or numpy objects.
The solution is to replace the filetable attribute with an id, filetable.id() which is already defined (if cdms2 barfs on this, make a string out of it, there's already a method for that).  Keep a global dictionary so that we can recover the filetable from its id.  There dictionary can be built where basic_filetable() is built.  There are a bunch of places where we would have to replace a :filetable reference with a dictionary lookup.

**Comment by doutriaux1** [comment]
@painter1 that's the solution forthe metrics package but I would like a more general solution at the cdms2 level in case somebody else try to do something similar.
