### ISSUE TITLE
Color legend extension does not provide continous color when using colormap

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/uvcdat#2173]
While testing 2.10, I've found that extending legend using ext_1 and ext_2 option may have issue. It looks okay when ext_1 and ext_2 options are used with the default color map. However if I apply different color map instead of the default one it gives noncontinuous colors for the extension part, triangles at sides.  

Below is the case using default color map:

```
import vcs
import cdms2
f=cdms2.open('./test_data/clt.nc')
d=f('clt')
x=vcs.init()

iso = x.createisofill()
iso.levels = range(0,110,10)
iso.ext_1 = 'y'  
iso.ext_2 = 'y'

x.plot(d,iso)
```
![test1](https://cloud.githubusercontent.com/assets/17091564/25829211/b121e1ca-3409-11e7-9c12-b828b58b67cb.png)

However if apply different color map than the default one:

```
x.clear()
x.setcolormap('bl_to_darkred')
iso = x.createisofill()
iso.levels = range(0,110,10)
iso.ext_1 = 'y'  
iso.ext_2 = 'y' 

x.plot(d,iso)
```

![test2](https://cloud.githubusercontent.com/assets/17091564/25829213/b6330392-3409-11e7-9f39-051608b97ec3.png)

See the color legend at bottom, note that the far left and far right triangle does not have continuous colors.

**Comment by doutriaux1** [comment]
@lee1043 this is because since 2.8 vcs is using the full range of colors (0,255) since we can use string names or rgb for colors. Your colormap has been designed for the old vcs hence you need to use the range(16,240) to select colors
I recommend.

``python
x.clear()
x.setcolormap('bl_to_darkred')
iso = x.createisofill()
levels = list(range(0,110,10))
# Adding -1.e20 / 1.e20 at ends of levels turns extensions on
levels.insert(0,-1.e20)
levels.append(1.e20)
iso.levels = levels
colors = vcs.getcolors(levels,colors=range(16,240))
iso.fillareacolors = colors
x.plot(d,iso)
```

**Comment by lee1043** [comment]
@doutriaux1 Thanks for inform, but I prefer the previous way of adding extension and select color map which is more explicit for users. Any plan to make the previous way available?

**Comment by doutriaux1** [comment]
@lee1043 sorry about this, I don't think we will switch back to using less colors. @aashish24 @sankhesh we could provide a 255 color version of the *old
* 240 colors versions? Would that help @lee1043
