### ISSUE TITLE
ParaView's VTK a bit behind default's build VTK.

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#903]
when using BUILD_MODE=ALL ParaView is built and the VTK built is not our VTK.

**Comment by doutriaux1** [comment]
@aashish24 you're taking a look at this right?

**Comment by doutriaux1** [comment]
also you're going to add the -DCDAT_BUILD_PARAVIEW=ON option right? So it builds always VTK by default even for CDAT_BUILD_MODE=ALL

**Comment by dlonie** [comment]
@chaosphere2112 @doutriaux1 @aashish24 

We were having this discussion somewhere, but I can't find it now...this looks like a good spot to pick it up.

It would be much easier to just keep VTK in the superbuild and not worry about syncing forking ParaView. Since paraview uses VTK as a git submodule, we'd need to fork both and keep everything sync'd with our changes as well as upstream. This is doable, but at quite a maintenance cost. Also, the decision to choose ParaView vs VTK at build time is not obvious and may be confusing for new users; I'm a developer on this project, and I don't even really know when ParaView should be used, nor what functionality we may be pulling from it. To me, it looks like we don't really need the burden or the build complexity that the ability to switch backends brings.

So my question: What do we need from ParaView? It hasn't been up-to-date in a while, and aside from "FULL" builds not working, I haven't seen/heard any complaints about this. Is there any actual loss in functionality that we get from solely using VTK?

**Comment by doutriaux1** [comment]
@dlonie not that I know of. I thought uvcdat-web used it it with paravieweb, but @jbeezley stated it's not. @ThomasMaxwell is looking inot // processing using it, but I don't know where that is at.
As far as I know we don't use ParaView anywhere at the moment. @aashish24 any reason to keep it around (at least until we really need it)?

**Comment by chaosphere2112** [comment]
@dlonie @doutriaux1 I'm certainly not using it for anything in particular. I, too, was under the impression that it was in use in cdatweb, but @jbeezley is the guy who knows what's going on there.

**Comment by jbeezley** [comment]
Actually, I just noticed today that you cannot run cdatweb when Paraview is enabled because it lacks one of the patches I put into VTK.  From the CMake configuration, it looked to me that Paraview was necessary for parallel builds.  I'm not sure if that is still true or not.

**Comment by doutriaux1** [comment]
ok let's wait to hear from @aashish24 or @ThomasMaxwell but I'll issue a PR to remove this for now. Actually @aashish24 is supposed to do this for a while now. I'll just go ahead and do it for him.
