### ISSUE TITLE
UV-CDAT code test coverage

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#922]
@doutriaux1 @aashish24 I think this might be something worth taking at look at http://blog.coveralls.io/2012/12/14/Coveralls-Open/

It seems to integrate neatly with Travis..

**Comment by durack1** [comment]
@doutriaux1 another 2.3 candidate..

**Comment by durack1** [comment]
@dnadeau4 just pinging you on this issue/query as test coverage might be something that may be useful within `cdms2` updates..

**Comment by dnadeau4** [comment]
I'll take a look I think we really need something like this.

**Comment by doutriaux1** [comment]
@chaosphere2112 to add to list of 3.0 new things

**Comment by durack1** [comment]
@chaosphere2112 pinging you here.. Should this be a `2.6er`?

**Comment by chaosphere2112** [comment]
@durack1 I actually have this almost entirely ready in a branch. I'll try and formalize it and submit a PR in the next couple of days.

**Comment by durack1** [comment]
@chaosphere2112 even better! The versioneye service is pay for service.

**Comment by chaosphere2112** [comment]
@durack1 Wrong issue :wink:

**Comment by durack1** [comment]
@chaosphere2112 not really https://github.com/UV-CDAT/uvcdat/issues/922#issuecomment-64206531, but it should be - I'll purge that (versioneye) comment as it's been moved to a new dedicated one #1842

**Comment by durack1** [comment]
@chaosphere2112 is this fixed, I think you did in #1851? If so wanna close?

**Comment by aashish24** [comment]
@durack1 we can close this one. There is anohter issue I need to create is on submitting covergage to cdash but i will file another issue for it.

**Comment by durack1** [comment]
@aashish24 I would have kept this open as the `cdash` reporting is part of a "final" solution I would have guessed? What's the point in creating another issue entry for the same thing?

**Comment by aashish24** [comment]
> @aashish24 I would have kept this open as the cdash reporting is part of a "final" solution I would have guessed? What's the point in creating another issue entry for the same thing?

I think its better to have fine level resolution in general than try to have a issue that is long standing. Also, I think I would argue that we do have to the coverage now. Now having them reported to CDASH is a different problem.

**Comment by durack1** [comment]
@aashish24 fair enough, but closing one issue and opening another is status quo in making progress against the 2.6 milestone..

**Comment by aashish24** [comment]
> @aashish24 fair enough, but closing one issue and opening another is status quo in making progress against the 2.6 milestone..

yes and so. I think if we have a decent size task or a task that can be implemented in sub-tasks, we should list all of them and mark them done as finish them. It keeps the PR small and keeps the momentum going. In fact I encourage folks to do smaller PR's as much as possible. In this case, since it wasn't really planned but we had some code that could do the first step in complete code coverage stuff, I thought its good to split the tasks since reporting and code that actually find the coverage could easily be two tasks.

**Comment by durack1** [comment]
@doutriaux1 @aashish24 not sure this is implemented, it seems similar to `travis` you can also get badges and reporting - see https://coveralls.io/builds/7049632 for e.g.

**Comment by doutriaux1** [comment]
@chaosphere2112 can we link to coverall?

**Comment by chaosphere2112** [comment]
@doutriaux1 Yes... here are the steps we'll need to do:

1. Fix Travis so it actually works (probably should just go with -nox)
2. Fix the coverage measurement (appears to have broken since the conda build)
3. Build using -DCDAT_MEASURE_COVERAGE=ON
3. Add a post step to run the `coverage_report` script
3. Run a coveralls client to upload the coverage data to coveralls

**Comment by doutriaux1** [comment]
yes `nox` is already being used by pmp and uvcmetrics it works perfectly

**Comment by doutriaux1** [comment]
see `coverage_back` branch for a begining of putting coverage back in

**Comment by doutriaux1** [comment]
I guess I will switch to nox in that branch as well
