### ISSUE TITLE
color map error

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#957]
I tried to apply a new color map to a plot (isofill quick). Got this when I clicked "apply"

Looks like it is trying to save it in the install directory (/usr/local/uvcdat.....)

Jerry

```
Traceback (most recent call last):
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/colormapEditorWidget.py", line 361, in save
    cmap.script(out)
  File "/usr/local/uvcdat/2.1.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/colormap.py", line 306, in script
    f = open(script_filename,mode)
IOError: [Errno 13] Permission denied: PyQt4.QtCore.QString(u'.json')
```

**Comment by potter2** [comment]
OSX 10.10  UVCDAT 2.1.0 (latest - just built today 1-10-14)

**Comment by williams13** [comment]
We need to make sure the saved files are going to the user's .uvcdat directory and not /usr/local/uvcdat/2.1.0.

-Dean

**Comment by hgohil2805** [comment]
Jerry,

I tried to apply a new color map to a quick iso fill and it worked fine for me. Based on the trace back it looks like the 'save' function is being called. That part of the code is not called when we use 'apply'.
Can you try and reproduce the error again? If you can.. can you please list the steps so that I can try them here.

**Comment by remram44** [comment]
> IOError: [Errno 13] Permission denied: PyQt4.QtCore.QString(u'.json')

This looks like a code issue, a filename not casted from QString to str/unicode?

**Comment by remram44** [comment]
This is still pending.
